### ISSUE TITLE
We can no longer create projects offline or outside the ABC network

### ISSUE THREAD

**Issue by colingourlay** [abcnews/aunty#189]
The deploy path checking stuff that @phocks introduced is awesome, because it greatly reduces the likelihood that we'll overwrite something that exists, but it now has an unfortunate (though rarely-triggered) side-effect.

If you try to create a new project either offline, or outside the ABC network (while not connected to the VPN), setup hangs after the "What is your project called?" prompt, with no feedback indicating that it's unable to connect to ContentFTP.

I propose that there should be a grace period after which time it throws up a warning about being unable to check for the existence of the project, and that we should manually verify before continuing (or ignore the advice if we're creating one of those rare projects we don't actually intend to deploy to ContentFTP).

**Comment by phocks** [comment]
Oh no, I thought I'd done something so that it fails gracefully when we're not on the network. Maybe not. I'll take a look. Thanks for pointing this out. I vaguely remember coding in a "warning, could not check ftp, possibility of remote overwrite" but I may not have.

I also noticed it hang for a bit when I tried deploying off network just before, but I ctrl-c quit out before it could time out unfortunately so I didn't get to see the timeout behaviour.

I'll make sure this is all sorted. I remember wondering what the best behaviour would be. Perhaps just warn and prompt the user to double check there's no existing remote directories.

I think this is another case where a UUID could come in handy that matches up with local and remote locations to really be sure it's the same project.

**Comment by colingourlay** [comment]
@phocks your latest PR brings up an interesting way to approach this. Maybe it should _fail_ when there's no network connectivity, but we enable the `--force` flag here to bypass the check.

**Comment by phocks** [comment]
Here's where the warning is @colingourlay and yes now I see what has probably happened. I was testing the FTP error in the office by turning off wifi, and it does indeed throw this error when there is no internet connection. But when at home and off the VPN it seems to try to connect (possibly it will timeout eventually) https://github.com/abcnews/aunty/blob/b2c2fff84e52d866d3d88467bf1edf54b8a6d991/src/generators/project/index.js#L67-L72
